### ISSUE TITLE
添加备注请求

### ISSUE THREAD

**Issue by WM9116** [kosakarin/play_together#4]
你好，在用你的项目，非常好，请问有没有想法加一个备注。要上车的人，可以添加一项备注（可选）比如：
 备注自己的游戏ID等。
例如 ：[@bot]上车 [房间编号]或[@创建者] 备注(可选)
然后，当房主或者其他人发送[查车]指令时 ，则发送

您当前所在房间编号：**********
房间名称：人民广场风云再起
房间密钥：舞萌地插排队用
房间人数：不限制
已加入的成员：
    111(**111********) 备注
    222(222**********) 备注
房间自动解散剩余时间：7分钟

当然开车人开车时 可能也可以额外填写备注

最后谢谢您的项目！！1

**Comment by kosakarin** [comment]
上车的命令不太好改动了，再改动有些过于复杂了。
我可以单独写一个添加备注的命令

**Comment by kosakarin** [comment]
已添加[添加个性化备注 #5](https://github.com/kosakarin/play_together/pull/5)

**Comment by WM9116** [comment]
好的，谢谢！
